apiVersion: v1
kind: Pod
metadata:
  name: "xiaozhan-pytorch-pod"
  labels:
    app: mytest
spec:
  securityContext:
    runAsUser: 0
    fsGroup: 0
  containers:
  - name: "xiaozhan-pytorch-pod"
    image: docker.artifactory-test.corp.linkedin.com/tensorflow/xiaozhan-pytorch:0.0.6
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
    command: ["sleep", "infinity"]
    env:
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: "compute,utility"
      - name: NVIDIA_REQUIRE_CUDA
        value: "cuda>=9.1"

